# Generated by Django 5.1.1 on 2024-09-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rates",
            fields=[
                (
                    "rate_id",
                    models.IntegerField(
                        help_text="Unique identifier for the rate",
                        primary_key=True,
                        serialize=False,
                        verbose_name="rate_id",
                    ),
                ),
                (
                    "rate_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation date of the rate",
                        verbose_name="rate_date",
                    ),
                ),
                (
                    "rate_email",
                    models.CharField(
                        help_text="Email of the user who rated, 'Anonymous' if skipped validation",
                        max_length=255,
                        verbose_name="rate_email",
                    ),
                ),
                (
                    "rate_value",
                    models.IntegerField(
                        help_text="Value of the rate", verbose_name="rate_value"
                    ),
                ),
            ],
        ),
    ]
