# Generated by Django 5.1.1 on 2024-09-28 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Universities",
            fields=[
                (
                    "university_id",
                    models.IntegerField(
                        help_text="Unique identifier for the university",
                        primary_key=True,
                        serialize=False,
                        verbose_name="university_id",
                    ),
                ),
                (
                    "university_name",
                    models.CharField(
                        help_text="Name of the university",
                        max_length=255,
                        verbose_name="university_name",
                    ),
                ),
                (
                    "university_campus",
                    models.CharField(
                        help_text="Campus of the university",
                        max_length=255,
                        verbose_name="university_campus",
                    ),
                ),
                (
                    "university_country",
                    models.CharField(
                        help_text="Country of the university",
                        max_length=255,
                        verbose_name="university_country",
                    ),
                ),
                (
                    "university_state",
                    models.CharField(
                        help_text="State of the university",
                        max_length=255,
                        verbose_name="university_state",
                    ),
                ),
                (
                    "university_city",
                    models.CharField(
                        help_text="City of the university",
                        max_length=255,
                        verbose_name="university_city",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rates",
            name="rate_university_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="rates.universities",
            ),
            preserve_default=False,
        ),
    ]
