# Generated by Django 5.1.1 on 2024-10-02 22:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0002_universities_rates_rate_university_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="rates",
            name="rate_validated",
            field=models.BooleanField(
                default=False,
                help_text="If the email was validated or not, see the user flow diagram",
                verbose_name="rate_validated",
            ),
        ),
        migrations.AlterField(
            model_name="rates",
            name="rate_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier for the rate",
                primary_key=True,
                serialize=False,
                verbose_name="rate_id",
            ),
        ),
        migrations.AlterField(
            model_name="universities",
            name="university_campus",
            field=models.CharField(
                help_text="Campus of the university, a university can have campuses in different cities or different places of the city",
                max_length=255,
                verbose_name="university_campus",
            ),
        ),
    ]
