# Generated by Django 5.1.1 on 2024-10-04 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0003_rates_rate_validated_alter_rates_rate_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="universities",
            name="university_campus",
        ),
        migrations.AddField(
            model_name="universities",
            name="university_acronym",
            field=models.CharField(
                help_text="Acronym of the university e.g: 'MIT' for 'Massachusetts Institute of Technology'",
                max_length=255,
                null=True,
                verbose_name="university_acronym",
            ),
        ),
        migrations.AddField(
            model_name="universities",
            name="university_source_id",
            field=models.CharField(
                default=0,
                help_text="Unique identifier for the university in the source data usually the source API or the data provider (e.g: government)",
                max_length=255,
                verbose_name="university_source_id",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rates",
            name="rate_email",
            field=models.CharField(
                help_text="Email of the user who rated, 'NULL' if skipped validation",
                max_length=255,
                null=True,
                verbose_name="rate_email",
            ),
        ),
        migrations.AlterField(
            model_name="rates",
            name="rate_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                verbose_name="rate_id",
            ),
        ),
        migrations.AlterField(
            model_name="rates",
            name="rate_university_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rates.universities",
                verbose_name="rate_university_id",
            ),
        ),
        migrations.AlterField(
            model_name="universities",
            name="university_city",
            field=models.CharField(
                help_text="City of the university, lower for the contry to in ISO 3166-2 or as definied by the source data",
                max_length=255,
                verbose_name="university_city",
            ),
        ),
        migrations.AlterField(
            model_name="universities",
            name="university_country",
            field=models.CharField(
                help_text="Country of the university in ISO 3166-1 name (English) format",
                max_length=255,
                verbose_name="university_country",
            ),
        ),
        migrations.AlterField(
            model_name="universities",
            name="university_id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="university_id"
            ),
        ),
        migrations.AlterField(
            model_name="universities",
            name="university_state",
            field=models.CharField(
                help_text="State of the university, middle for the contry to in ISO 3166-2 or as definied by the source data",
                max_length=255,
                null=True,
                verbose_name="university_state",
            ),
        ),
    ]
